# Generated by Django 2.2 on 2019-07-17 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'polus'), (2, 'company'), (3, 'department')]),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rules', models.ManyToManyField(related_name='resumes_rules', to='mainapp.Rule')),
            ],
        ),
    ]
